// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHTx_0fIRFIs70Kr6MEAgvFqEQgg6N7_I',
    appId: '1:35461838725:web:821a005b886b23694a76ec',
    messagingSenderId: '35461838725',
    projectId: 'se380-richyrich',
    authDomain: 'se380-richyrich.firebaseapp.com',
    storageBucket: 'se380-richyrich.firebasestorage.app',
    measurementId: 'G-GD675B6YTG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtPM-1H7x3T9ZHmJ0cBEgoRjJX-7t00VA',
    appId: '1:35461838725:android:92a62bbeb1d4b7b04a76ec',
    messagingSenderId: '35461838725',
    projectId: 'se380-richyrich',
    storageBucket: 'se380-richyrich.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBneZrOA-ihgYmbvYkAT33Qt8mV-ZjCsYw',
    appId: '1:35461838725:ios:aa5f95d768e5a5d04a76ec',
    messagingSenderId: '35461838725',
    projectId: 'se380-richyrich',
    storageBucket: 'se380-richyrich.firebasestorage.app',
    iosBundleId: 'com.example.se380Richyrich',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBneZrOA-ihgYmbvYkAT33Qt8mV-ZjCsYw',
    appId: '1:35461838725:ios:aa5f95d768e5a5d04a76ec',
    messagingSenderId: '35461838725',
    projectId: 'se380-richyrich',
    storageBucket: 'se380-richyrich.firebasestorage.app',
    iosBundleId: 'com.example.se380Richyrich',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAHTx_0fIRFIs70Kr6MEAgvFqEQgg6N7_I',
    appId: '1:35461838725:web:96fc64b46883249b4a76ec',
    messagingSenderId: '35461838725',
    projectId: 'se380-richyrich',
    authDomain: 'se380-richyrich.firebaseapp.com',
    storageBucket: 'se380-richyrich.firebasestorage.app',
    measurementId: 'G-C6V7EC9YJ9',
  );
}
